# syntax=docker/dockerfile:1
ARG PLONE_VERSION=undefined
FROM plone/server-builder:${PLONE_VERSION} AS builder

WORKDIR /app


# Add local code
COPY scripts/ scripts/
COPY . src

# Install local requirements and pre-compile mo files
RUN <<EOT
    set -e
    bin/pip install mxdev uv
    sed -i 's/-e .\[test\]/./g' src/mx.ini
    cd /app/src
    # remove potentially existing virtualenv from local build
    rm -rf .venv
    ../bin/mxdev -c mx.ini
    ../bin/uv pip install -r requirements-mxdev.txt
    ../bin/python /compile_mo.py
EOT

FROM plone/server-acceptance:${PLONE_VERSION}

LABEL maintainer="CodeSyntax <plone@codesyntax.com>" \
    org.label-schema.name="ghcr.io/codesyntax/voltobootstraptheme-backend-acceptance" \
    org.label-schema.description="cs.volto.bootstraptheme backend acceptance image." \
    org.label-schema.vendor="CodeSyntax"

ENV CONFIGURE_PACKAGES="plone.restapi,plone.volto,plone.volto.cors,cs.volto.bootstraptheme"
ENV APPLY_PROFILES="cs.volto.bootstraptheme:acceptance"

# Copy /app from builder
COPY --from=builder /app /app

RUN <<EOT
    set -e
    ln -s /data /app/var
EOT
